
package com.founder.syrkgl.webservice.jwry.loginservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginServiceSoap", targetNamespace = "http://www.taiji.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://www.taiji.com.cn/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.loginservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.loginservice.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param password
     * @param loginName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.taiji.com.cn/login")
    @WebResult(name = "loginResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.loginservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.loginservice.LoginResponse")
    public String login(
        @WebParam(name = "loginName", targetNamespace = "http://www.taiji.com.cn/")
        String loginName,
        @WebParam(name = "password", targetNamespace = "http://www.taiji.com.cn/")
        String password);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetIP", action = "http://www.taiji.com.cn/GetIP")
    @WebResult(name = "GetIPResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "GetIP", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.loginservice.GetIP")
    @ResponseWrapper(localName = "GetIPResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.loginservice.GetIPResponse")
    public String getIP();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.taiji.com.cn/logout")
    @WebResult(name = "logoutResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "logout", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.loginservice.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.loginservice.LogoutResponse")
    public boolean logout();

}
