
package com.founder.syrkgl.webservice.jwry.residence;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Residence", targetNamespace = "http://www.taiji.com.cn/", wsdlLocation = "http://10.78.27.219/PEWebService_cs/Residence.asmx?WSDL")
public class Residence
    extends Service
{

    private final static URL RESIDENCE_WSDL_LOCATION;
    private final static WebServiceException RESIDENCE_EXCEPTION;
    private final static QName RESIDENCE_QNAME = new QName("http://www.taiji.com.cn/", "Residence");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.78.27.219/PEWebService_cs/Residence.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESIDENCE_WSDL_LOCATION = url;
        RESIDENCE_EXCEPTION = e;
    }

    public Residence() {
        super(__getWsdlLocation(), RESIDENCE_QNAME);
    }

    public Residence(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESIDENCE_QNAME, features);
    }

    public Residence(URL wsdlLocation) {
        super(wsdlLocation, RESIDENCE_QNAME);
    }

    public Residence(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESIDENCE_QNAME, features);
    }

    public Residence(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Residence(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResidenceSoap
     */
    @WebEndpoint(name = "ResidenceSoap")
    public ResidenceSoap getResidenceSoap() {
        return super.getPort(new QName("http://www.taiji.com.cn/", "ResidenceSoap"), ResidenceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResidenceSoap
     */
    @WebEndpoint(name = "ResidenceSoap")
    public ResidenceSoap getResidenceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.taiji.com.cn/", "ResidenceSoap"), ResidenceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ResidenceSoap
     */
    @WebEndpoint(name = "ResidenceSoap12")
    public ResidenceSoap getResidenceSoap12() {
        return super.getPort(new QName("http://www.taiji.com.cn/", "ResidenceSoap12"), ResidenceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResidenceSoap
     */
    @WebEndpoint(name = "ResidenceSoap12")
    public ResidenceSoap getResidenceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.taiji.com.cn/", "ResidenceSoap12"), ResidenceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESIDENCE_EXCEPTION!= null) {
            throw RESIDENCE_EXCEPTION;
        }
        return RESIDENCE_WSDL_LOCATION;
    }

}
