
package com.founder.syrkgl.webservice.jwry.residence;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ResidenceSoap", targetNamespace = "http://www.taiji.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResidenceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://www.taiji.com.cn/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param condition
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.ReportResidenceInfo
     */
    @WebMethod(operationName = "QueryInfo", action = "http://www.taiji.com.cn/QueryInfo")
    @WebResult(name = "QueryInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "QueryInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.QueryInfo")
    @ResponseWrapper(localName = "QueryInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.QueryInfoResponse")
    public ReportResidenceInfo queryInfo(
        @WebParam(name = "condition", targetNamespace = "http://www.taiji.com.cn/")
        ConditionForResideInfo condition);

    /**
     * 
     * @param conditionfordownload
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.ResidenceInfoReturn
     */
    @WebMethod(operationName = "DownLoadInfo", action = "http://www.taiji.com.cn/DownLoadInfo")
    @WebResult(name = "DownLoadInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "DownLoadInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DownLoadInfo")
    @ResponseWrapper(localName = "DownLoadInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DownLoadInfoResponse")
    public ResidenceInfoReturn downLoadInfo(
        @WebParam(name = "conditionfordownload", targetNamespace = "http://www.taiji.com.cn/")
        ConditionForDownLoad conditionfordownload);

    /**
     * 
     * @param conditionfordownload
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.ResidenceInfoReturn
     */
    @WebMethod(operationName = "DownLoadInfoForFM", action = "http://www.taiji.com.cn/DownLoadInfoForFM")
    @WebResult(name = "DownLoadInfoForFMResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "DownLoadInfoForFM", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DownLoadInfoForFM")
    @ResponseWrapper(localName = "DownLoadInfoForFMResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DownLoadInfoForFMResponse")
    public ResidenceInfoReturn downLoadInfoForFM(
        @WebParam(name = "conditionfordownload", targetNamespace = "http://www.taiji.com.cn/")
        ConditionForDownLoad conditionfordownload);

    /**
     * 
     * @param conditionforReceiveData
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "ReceiveData", action = "http://www.taiji.com.cn/ReceiveData")
    @WebResult(name = "ReceiveDataResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "ReceiveData", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReceiveData")
    @ResponseWrapper(localName = "ReceiveDataResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReceiveDataResponse")
    public OperationReturn receiveData(
        @WebParam(name = "conditionforReceiveData", targetNamespace = "http://www.taiji.com.cn/")
        ConditionForReceiveData conditionforReceiveData);

    /**
     * 
     * @param conditionForQueryRecordInfo
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.RecordInfo
     */
    @WebMethod(operationName = "QueryRecordInfo", action = "http://www.taiji.com.cn/QueryRecordInfo")
    @WebResult(name = "QueryRecordInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "QueryRecordInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.QueryRecordInfo")
    @ResponseWrapper(localName = "QueryRecordInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.QueryRecordInfoResponse")
    public RecordInfo queryRecordInfo(
        @WebParam(name = "conditionForQueryRecordInfo", targetNamespace = "http://www.taiji.com.cn/")
        ConditionForQueryRecordInfo conditionForQueryRecordInfo);

    /**
     * 
     * @param info
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "ReporteResidenceInfo", action = "http://www.taiji.com.cn/ReporteResidenceInfo")
    @WebResult(name = "ReporteResidenceInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "ReporteResidenceInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteResidenceInfo")
    @ResponseWrapper(localName = "ReporteResidenceInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteResidenceInfoResponse")
    public OperationReturn reporteResidenceInfo(
        @WebParam(name = "info", targetNamespace = "http://www.taiji.com.cn/")
        ReportResidenceInfo info);

    /**
     * 
     * @param info
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "ReporteResidenceInfoForFM", action = "http://www.taiji.com.cn/ReporteResidenceInfoForFM")
    @WebResult(name = "ReporteResidenceInfoForFMResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "ReporteResidenceInfoForFM", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteResidenceInfoForFM")
    @ResponseWrapper(localName = "ReporteResidenceInfoForFMResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteResidenceInfoForFMResponse")
    public OperationReturn reporteResidenceInfoForFM(
        @WebParam(name = "info", targetNamespace = "http://www.taiji.com.cn/")
        ReportResidenceInfo info);

    /**
     * 
     * @param info
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "ReporteInhabitancyInfo", action = "http://www.taiji.com.cn/ReporteInhabitancyInfo")
    @WebResult(name = "ReporteInhabitancyInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "ReporteInhabitancyInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteInhabitancyInfo")
    @ResponseWrapper(localName = "ReporteInhabitancyInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteInhabitancyInfoResponse")
    public OperationReturn reporteInhabitancyInfo(
        @WebParam(name = "info", targetNamespace = "http://www.taiji.com.cn/")
        Inhabitancy info);

    /**
     * 
     * @param info
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "ReporteWorkplaceInfo", action = "http://www.taiji.com.cn/ReporteWorkplaceInfo")
    @WebResult(name = "ReporteWorkplaceInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "ReporteWorkplaceInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteWorkplaceInfo")
    @ResponseWrapper(localName = "ReporteWorkplaceInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteWorkplaceInfoResponse")
    public OperationReturn reporteWorkplaceInfo(
        @WebParam(name = "info", targetNamespace = "http://www.taiji.com.cn/")
        Workplace info);

    /**
     * 
     * @param info
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "ReporteManageInfo", action = "http://www.taiji.com.cn/ReporteManageInfo")
    @WebResult(name = "ReporteManageInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "ReporteManageInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteManageInfo")
    @ResponseWrapper(localName = "ReporteManageInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.ReporteManageInfoResponse")
    public OperationReturn reporteManageInfo(
        @WebParam(name = "info", targetNamespace = "http://www.taiji.com.cn/")
        ManageInfo info);

    /**
     * 
     * @param conditionFordeleteResidenceInfo
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "DeleteResidenceInfo", action = "http://www.taiji.com.cn/DeleteResidenceInfo")
    @WebResult(name = "DeleteResidenceInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "DeleteResidenceInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DeleteResidenceInfo")
    @ResponseWrapper(localName = "DeleteResidenceInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DeleteResidenceInfoResponse")
    public OperationReturn deleteResidenceInfo(
        @WebParam(name = "conditionFordeleteResidenceInfo", targetNamespace = "http://www.taiji.com.cn/")
        ConditionFordeleteResidenceInfo conditionFordeleteResidenceInfo);

    /**
     * 
     * @param conditionForDeleteInhabitancy
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "DeleteInhabitancy", action = "http://www.taiji.com.cn/DeleteInhabitancy")
    @WebResult(name = "DeleteInhabitancyResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "DeleteInhabitancy", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DeleteInhabitancy")
    @ResponseWrapper(localName = "DeleteInhabitancyResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DeleteInhabitancyResponse")
    public OperationReturn deleteInhabitancy(
        @WebParam(name = "conditionForDeleteInhabitancy", targetNamespace = "http://www.taiji.com.cn/")
        ConditionForDeleteInhabitancy conditionForDeleteInhabitancy);

    /**
     * 
     * @param conditionForDeleteWorkplace
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "DeleteWorkplace", action = "http://www.taiji.com.cn/DeleteWorkplace")
    @WebResult(name = "DeleteWorkplaceResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "DeleteWorkplace", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DeleteWorkplace")
    @ResponseWrapper(localName = "DeleteWorkplaceResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DeleteWorkplaceResponse")
    public OperationReturn deleteWorkplace(
        @WebParam(name = "conditionForDeleteWorkplace", targetNamespace = "http://www.taiji.com.cn/")
        ConditionForDeleteWorkplace conditionForDeleteWorkplace);

    /**
     * 
     * @param conditionForDeleteManageInfo
     * @return
     *     returns com.founder.syrkgl.webservice.jwry.residence.OperationReturn
     */
    @WebMethod(operationName = "DeleteManageInfo", action = "http://www.taiji.com.cn/DeleteManageInfo")
    @WebResult(name = "DeleteManageInfoResult", targetNamespace = "http://www.taiji.com.cn/")
    @RequestWrapper(localName = "DeleteManageInfo", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DeleteManageInfo")
    @ResponseWrapper(localName = "DeleteManageInfoResponse", targetNamespace = "http://www.taiji.com.cn/", className = "com.founder.syrkgl.webservice.jwry.residence.DeleteManageInfoResponse")
    public OperationReturn deleteManageInfo(
        @WebParam(name = "conditionForDeleteManageInfo", targetNamespace = "http://www.taiji.com.cn/")
        ConditionForDeleteManageInfo conditionForDeleteManageInfo);

}
