[
{"id":"01","text":"等于","py":"DY"},
{"id":"02","text":"不等于","py":"BDY"},
{"id":"03","text":"大于等于","py":"DYDY"},
{"id":"04","text":"大于","py":"DY"},
{"id":"05","text":"小于等于","py":"XYDY"},
{"id":"06","text":"小于","py":"XY"},
{"id":"07","text":"包含","py":"BH"},
{"id":"08","text":"不包含","py":"BBH"},
{"id":"09","text":"为空","py":"WK"},
{"id":"10","text":"不为空","py":"BWK"}
]