
package com.founder.framework.message.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ITipInfoWebService", targetNamespace = "http://tip.webservice.portal.modules.portal.magic.com/")
public interface ITipInfoWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testOK", targetNamespace = "http://tip.webservice.portal.modules.portal.magic.com/", className = "com.demo.TestOK")
    @ResponseWrapper(localName = "testOKResponse", targetNamespace = "http://tip.webservice.portal.modules.portal.magic.com/", className = "com.demo.TestOKResponse")
    public String testOK(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendTip", targetNamespace = "http://tip.webservice.portal.modules.portal.magic.com/", className = "com.demo.SendTip")
    @ResponseWrapper(localName = "sendTipResponse", targetNamespace = "http://tip.webservice.portal.modules.portal.magic.com/", className = "com.demo.SendTipResponse")
    public String sendTip(
        @WebParam(name = "arg0", targetNamespace = "")
        TipBean arg0);

}
