
package com.founder.framework.message.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "TipInfoWebServiceImplService", targetNamespace = "http://tip.webservice.portal.modules.portal.magic.com/", wsdlLocation = "http://10.78.5.166:8080/magic_portal_war/ws/tipInfoWebServiceImpl?wsdl")
public class TipInfoWebServiceImplService
    extends Service
{

    private final static URL TIPINFOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://10.78.5.166:8080/magic_portal_war/ws/tipInfoWebServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TIPINFOWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TipInfoWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TipInfoWebServiceImplService() {
        super(TIPINFOWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://tip.webservice.portal.modules.portal.magic.com/", "TipInfoWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns ITipInfoWebService
     */
    @WebEndpoint(name = "TipInfoWebServiceImplPort")
    public ITipInfoWebService getTipInfoWebServiceImplPort() {
        return (ITipInfoWebService)super.getPort(new QName("http://tip.webservice.portal.modules.portal.magic.com/", "TipInfoWebServiceImplPort"), ITipInfoWebService.class);
    }

}
